export default [
  'strapi::logger',
  'strapi::errors',
  {
    name: 'strapi::cors',
    config: {
      enabled: true,
      origin: [
        'http://localhost:3000',
        'https://edusprinthub.com',
        'https://www.edusprinthub.com',
        'https://studybettertoday.com',
        'https://www.studybettertoday.com',
        'http://13.203.144.7',
        'https://13.203.144.7',
        'https://www.13.203.144.7',
        'http://www.13.203.144.7:1337',
      ],
      headers: ['*'],
      methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
      keepHeaderOnError: true,
    },
  },
  'strapi::security',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
